#!/usr/bin/env bash
# =============================================================================
#  NestBook — Cloudflare Tunnel Setup
#  Ubuntu 24.04 · Run as root from your home network SSH session
#
#  What this does:
#    1. Installs cloudflared
#    2. Authenticates with Cloudflare (manual browser step)
#    3. Creates a tunnel named nestbook-tunnel
#    4. Writes ~/.cloudflared/config.yml
#    5. Routes DNS for ssh.nestbook.io and nestbook.io
#    6. Installs cloudflared as a systemd service (auto-starts on reboot)
#    7. Prints client-side setup instructions
#
#  Log: /root/cloudflare-tunnel-setup.log
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
TUNNEL_NAME="nestbook-tunnel"
CF_DIR="/root/.cloudflared"
LOG_FILE="/root/cloudflare-tunnel-setup.log"
SSH_HOSTNAME="ssh.nestbook.io"
WEB_HOSTNAME="nestbook.io"
WWW_HOSTNAME="www.nestbook.io"

# ── Helpers ───────────────────────────────────────────────────────────────────
log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg" | tee -a "$LOG_FILE"
}

header() {
  echo "" | tee -a "$LOG_FILE"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | tee -a "$LOG_FILE"
  echo "  $*" | tee -a "$LOG_FILE"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | tee -a "$LOG_FILE"
}

ok()   { echo "  ✓  $*" | tee -a "$LOG_FILE"; }
info() { echo "  →  $*" | tee -a "$LOG_FILE"; }
warn() { echo "  ⚠  $*" | tee -a "$LOG_FILE"; }

pause() {
  echo ""
  echo "  Press ENTER to continue once you've completed the step above..."
  read -r
}

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root. Use: sudo bash $0"
  exit 1
fi

# ── Start ─────────────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$LOG_FILE")"
log "=== NestBook Cloudflare Tunnel Setup started ==="

header "STEP 1 — Install cloudflared"
log "Installing cloudflared..."

# Add Cloudflare GPG key and repo
mkdir -p /usr/share/keyrings
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
  | gpg --dearmor -o /usr/share/keyrings/cloudflare-main.gpg

echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main" \
  > /etc/apt/sources.list.d/cloudflared.list

apt-get update -qq
apt-get install -y cloudflared

CF_VERSION=$(cloudflared --version 2>&1 | head -1)
ok "cloudflared installed: $CF_VERSION"
log "cloudflared installed: $CF_VERSION"

# ── Step 2: Authenticate ──────────────────────────────────────────────────────
header "STEP 2 — Authenticate with Cloudflare (manual step)"
echo ""
echo "  cloudflared will now print a URL."
echo "  Open that URL in a browser, log in to your Cloudflare account,"
echo "  and select the domain: nestbook.io"
echo ""
echo "  After you authorise, come back here — the script continues automatically."
echo ""
pause

log "Running: cloudflared tunnel login"
cloudflared tunnel login

if [[ ! -f "$CF_DIR/cert.pem" ]]; then
  log "ERROR: Authentication failed — cert.pem not found at $CF_DIR"
  echo "ERROR: Authentication did not complete. Please re-run the script and complete the browser step."
  exit 1
fi

ok "Authentication complete. Credentials saved to $CF_DIR/cert.pem"
log "cert.pem found at $CF_DIR/cert.pem"

# ── Step 3: Create tunnel ─────────────────────────────────────────────────────
header "STEP 3 — Create tunnel: $TUNNEL_NAME"

# Check if tunnel already exists
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  warn "Tunnel '$TUNNEL_NAME' already exists — reusing it."
  log "Tunnel already exists, reusing."
else
  log "Creating tunnel: $TUNNEL_NAME"
  cloudflared tunnel create "$TUNNEL_NAME"
  ok "Tunnel created."
fi

# Get tunnel ID
TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')

if [[ -z "$TUNNEL_ID" ]]; then
  log "ERROR: Could not determine tunnel ID."
  echo "ERROR: Could not get tunnel ID. Check 'cloudflared tunnel list' manually."
  exit 1
fi

ok "Tunnel ID: $TUNNEL_ID"
log "Tunnel ID: $TUNNEL_ID"

# Find credentials file
CREDS_FILE="$CF_DIR/$TUNNEL_ID.json"
if [[ ! -f "$CREDS_FILE" ]]; then
  log "ERROR: Credentials file not found at $CREDS_FILE"
  echo "ERROR: Expected credentials file at $CREDS_FILE — not found."
  exit 1
fi
ok "Credentials file: $CREDS_FILE"

# ── Step 4: Write config ──────────────────────────────────────────────────────
header "STEP 4 — Write tunnel config"

CONFIG_FILE="$CF_DIR/config.yml"

cat > "$CONFIG_FILE" << EOF
# Cloudflare Tunnel config — NestBook
# Generated by setup-cloudflare-tunnel.sh on $(date '+%Y-%m-%d %H:%M:%S')

tunnel: $TUNNEL_ID
credentials-file: $CREDS_FILE

# Logging
loglevel: info
logfile: /var/log/cloudflared.log

ingress:
  # SSH — access from anywhere via: ssh -o ProxyCommand="cloudflared access ssh --hostname %h" root@$SSH_HOSTNAME
  - hostname: $SSH_HOSTNAME
    service: ssh://localhost:22

  # Web app — nestbook.io routed through nginx on port 80
  - hostname: $WEB_HOSTNAME
    service: http://localhost:80

  - hostname: $WWW_HOSTNAME
    service: http://localhost:80

  # Catch-all — required by cloudflared (must be last)
  - service: http_status:404
EOF

ok "Config written to $CONFIG_FILE"
log "Config written to $CONFIG_FILE"

# ── Step 5: Route DNS ─────────────────────────────────────────────────────────
header "STEP 5 — Create DNS records via Cloudflare API"
echo ""
info "This creates CNAME records in your Cloudflare DNS automatically."
info "Requires nestbook.io to be managed in the same Cloudflare account."
echo ""

log "Routing DNS: $SSH_HOSTNAME → tunnel"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$SSH_HOSTNAME" 2>&1 | tee -a "$LOG_FILE"; then
  ok "DNS routed: $SSH_HOSTNAME"
else
  warn "DNS routing failed for $SSH_HOSTNAME — add CNAME manually (see instructions below)."
fi

log "Routing DNS: $WEB_HOSTNAME → tunnel"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$WEB_HOSTNAME" 2>&1 | tee -a "$LOG_FILE"; then
  ok "DNS routed: $WEB_HOSTNAME"
else
  warn "DNS routing failed for $WEB_HOSTNAME — add CNAME manually (see instructions below)."
fi

log "Routing DNS: $WWW_HOSTNAME → tunnel"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$WWW_HOSTNAME" 2>&1 | tee -a "$LOG_FILE"; then
  ok "DNS routed: $WWW_HOSTNAME"
else
  warn "DNS routing failed for $WWW_HOSTNAME — add CNAME manually (see instructions below)."
fi

# ── Step 6: Install systemd service ──────────────────────────────────────────
header "STEP 6 — Install cloudflared as a systemd service"

log "Running: cloudflared service install"
cloudflared service install

systemctl enable cloudflared
systemctl restart cloudflared

sleep 2
STATUS=$(systemctl is-active cloudflared || true)
if [[ "$STATUS" == "active" ]]; then
  ok "cloudflared service is running."
  log "Service status: active"
else
  warn "Service status: $STATUS — check: journalctl -u cloudflared -n 50"
  log "Service status: $STATUS"
fi

# ── Step 7: Final instructions ────────────────────────────────────────────────
header "SETUP COMPLETE"

echo ""
echo "  Tunnel ID   : $TUNNEL_ID"
echo "  Tunnel name : $TUNNEL_NAME"
echo "  Config file : $CONFIG_FILE"
echo "  Log file    : /var/log/cloudflared.log"
echo ""
echo ""

cat << 'INSTRUCTIONS'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  MANUAL DNS RECORDS (if automatic routing failed above)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Go to Cloudflare → nestbook.io → DNS → Add records:

  Type    Name    Target                          Proxy
  ──────  ──────  ─────────────────────────────── ──────
  CNAME   ssh     <TUNNEL_ID>.cfargotunnel.com     ON
  CNAME   @       <TUNNEL_ID>.cfargotunnel.com     ON
  CNAME   www     <TUNNEL_ID>.cfargotunnel.com     ON

  Replace <TUNNEL_ID> with the tunnel ID shown above.
  Make sure the orange Cloudflare proxy cloud is ON for all three.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  HOW TO SSH IN FROM YOUR LAPTOP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. Install cloudflared on your laptop:

     Mac:     brew install cloudflare/cloudflare/cloudflared
     Windows: see server/scripts/install-cloudflared-windows.md
     Linux:   same apt steps as this script

  2. Add this to ~/.ssh/config on your laptop:

       Host ssh.nestbook.io
           ProxyCommand cloudflared access ssh --hostname %h
           User root
           IdentityFile ~/.ssh/id_rsa

  3. Connect from anywhere:

       ssh ssh.nestbook.io

     Works on school networks, through VPNs, behind firewalls —
     all traffic goes through Cloudflare over port 443 (HTTPS).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  USEFUL COMMANDS ON THE SERVER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Check tunnel status:   cloudflared tunnel info nestbook-tunnel
  View tunnel logs:      journalctl -u cloudflared -f
  Restart tunnel:        systemctl restart cloudflared
  List all tunnels:      cloudflared tunnel list

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INSTRUCTIONS

log "Setup complete."
echo ""
echo "  Full log saved to: $LOG_FILE"
echo ""
